name: Build and Post Github Releases
on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: actions/checkout@v3
      - name: Run Tests
        run: cargo test --verbose
      - name: Build Linux
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - name: Copy Assets folder to target dir
        run: cp -r assets target/x86_64-unknown-linux-gnu/release/
      - name: Copy to Current Dir
        run: cp -r target/x86_64-unknown-linux-gnu/release linux-latest  
      - name: Zip
        run: zip -D -r linux-latest.zip target/x86_64-unknown-linux-gnu/release/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-latest
          path: linux-latest.zip
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs:
      - test-and-build

    steps:
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
